### ISSUE TITLE
Error response from daemon: manifest for coomia/hadoop3.2-historyserver:0.2 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by andyuan1000** [spancer/bigdata-docker-builds#3]
[root@localhost hadoop3.2]# docker pull coomia/hadoop3.2-historyserver:0.2
Error response from daemon: manifest for coomia/hadoop3.2-historyserver:0.2 not found: manifest unknown: manifest unknown

**Comment by spancer** [comment]
the image doesn't exist, try using https://github.com/spancer/bigdata-docker-compose.
